### ISSUE TITLE
STD结果的PRcurve如何绘制？

### ISSUE THREAD

**Issue by SlamCabbage** [hku-mars/STD#28]
place_recognition_kitti.cpp中将每帧点云都作为关键帧，输出的结果中还是存在部分帧并没有找到一个回环结果，难以用于prcurve的绘制，请问作者是如何绘制的呢？能否提供代码呢？

**Comment by gongjun136** [comment]
> place_recognition_kitti.cpp中将每帧点云都作为关键帧，输出的结果中还是存在部分帧并没有找到一个回环结果，难以用于prcurve的绘制，请问作者是如何绘制的呢？能否提供代码呢？

我测试了STD提供的数据集，发现召回率并没有论文中的那么高，精准率确实高，不知道召回率怎么得到这么高的

**Comment by YuexinMu** [comment]
> place_recognition_kitti.cpp中将每帧点云都作为关键帧，输出的结果中还是存在部分帧并没有找到一个回环结果，难以用于prcurve的绘制，请问作者是如何绘制的呢？能否提供代码呢？

您好，请问您最后解决了怎么绘制PR曲线的问题吗？我使用真值位姿轨迹生成了回环真值，但是最后计算得到的PR曲线和论文中差异非常大，我觉得可能是我的计算方式有问题，想向您请教一下如何绘制该曲线
