### ISSUE TITLE
Ground-Truth of KA Urban East Dataset

### ISSUE THREAD

**Issue by Bazinga92445** [hku-mars/STD#3]
Thank you for sharing your newest research! I've been following your works for a while, and I really admire your previous achievements.
I noticed that KA Urban East, the dataset used for testing your algorithm on Livox Horizon LiDAR, doesn't contain the ground truth poses according to its site(https://isas-server.iar.kit.edu/lidardataset/). It maybe silly to ask, but how did you generate the gt data?
Looking forward to your reply, and hope your paper be accepted soon!

**Comment by ChongjianYUAN** [comment]
> 
We use the loop detection module and the graph optimization module to get a globally consistent map and calculate the gt value of the loop based on this.

**Comment by Bazinga92445** [comment]
Thanks, do you think different algorithms(loop detection, odometry, etc.) applied make obvious differences on the calculated gt result?

**Comment by ChongjianYUAN** [comment]
> Thanks, do you think different algorithms(loop detection, odometry, etc.) applied make obvious differences on the calculated gt result?

If you can get a consistent global map through your algorithm, I don't think there is a significant difference between different algorithms for gt calculation.

**Comment by Bazinga92445** [comment]
Thank you very much for your patient reply!
