### ISSUE TITLE
About octree leaves

### ISSUE THREAD

**Issue by YangSiri** [hku-mars/STD#5]
Hi，there

This work is excellent with detailed notes on codes as well. I wonder why you dont use the recut process which means splitting the octree root until it becomes a plane or reach the max depth. Is it useless and time-consuming? Are the fixed-resolution voxels enough for this task?

Thanks in advance.

**Comment by ChongjianYUAN** [comment]
> Hi，there
> 
> This work is excellent with detailed notes on codes as well. I wonder why you dont use the recut process which means splitting the octree root until it becomes a plane or reach the max depth. Is it useless and time-consuming? Are the fixed-resolution voxels enough for this task?
> 
> Thanks in advance.

Thanks for your suggestion. Fixed size voxel cutting achieved good results, at least in our test dataset. Therefore we don't use the recut process.

**Comment by YangSiri** [comment]
Thank you for your reply. 

May i ask in what situation do you think recut would be beneficial or vital?

**Comment by ChongjianYUAN** [comment]
> Thank you for your reply.
> 
> May i ask in what situation do you think recut would be beneficial or vital?

I think hybrid scenarios (e.g. outdoor+indoor, structured+unstructured) will require that.

**Comment by YangSiri** [comment]
Got it. Thank you.
