### ISSUE TITLE
Issue with No Corner 

### ISSUE THREAD

**Issue by chengwei0427** [hku-mars/STD#8]
Dear hku-mars team:

Thanks for your wonderfull work.

I'm trying to test STD on my own datasets with a velodyne16 lidar, and I meet a issue that I'm not achieving to resolve.
This is what I do:

1. I run a laserodm like **floam**, and publish the odom pose per scan.
2. Subscribe the laser data and odom, sync the laser and odom and cache the lidar in global frame as a keyframe(5m for a dense temp cloud) like the example.
Then generate STDescs with the function **GenerateSTDescs**, but I find that the **stds size: 0**.

 
![2023-03-23 16-48-37屏幕截图](https://user-images.githubusercontent.com/20199999/227150475-b409f0a7-5df4-4599-ac21-64db60b9dd92.png)

The cache keyFrame
![2023-03-23 16-50-28屏幕截图](https://user-images.githubusercontent.com/20199999/227150922-a52aab45-fc45-467d-b902-ea3b04846c73.png)

**Comment by chengwei0427** [comment]
Hi，
An email 《Scans》 has been sent to your mail;

Looking forward to your reply.

**Comment by ChongjianYUAN** [comment]
> Hi， An email 《Scans》 has been sent to your mail;
> 
> Looking forward to your reply.

I tried your dataset and the corner points extraction works fine in my test.
![velodyne_pcd](https://user-images.githubusercontent.com/51600805/227869647-cb94c551-f89e-4c76-a674-7ceddda9f0d5.png)
![terminal_output](https://user-images.githubusercontent.com/51600805/227873143-22292fc9-d4b2-478d-9047-3c21c6dc4ec3.png)
You can try this config for your dataset. Then you can get some loops.
![config](https://user-images.githubusercontent.com/51600805/227873540-2ab9c6bb-3b5b-4259-8036-ea5c5187d038.png)

![loop_example](https://user-images.githubusercontent.com/51600805/227873254-e2cefccf-6e8b-46a0-a442-0fa2f8c6da5e.png)

**Comment by chengwei0427** [comment]
Hi，Dr.Yuan,


Thanks for your reply.


After an in-depth examination, I find the params load is abnormal.It's my problem, and it's normal now.






Thanks again.

yours,
Chengwei Zhao


品一杯香茗、种一地阳光
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "hku-mars/STD"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Mar 27, 2023 03:40 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [hku-mars/STD] Issue with No Corner  (Issue #8)





  
Hi， An email 《Scans》 has been sent to your mail;
 
Looking forward to your reply.
  
I tried your dataset and the corner points extraction works fine in my test.
 
 
 You can try this config for your dataset. Then you can get some loops.

**Comment by chengwei0427** [comment]
Nice work! And a test [video](https://www.bilibili.com/video/BV1Wm4y1r74f/?spm_id_from=333.999.0.0&vd_source=438f630fe29bd5049b24c7f05b1bcaa3) is here.
Thank you for your help.
